SHOW DATABASES;

USE DEMO

CREATE DATABASE bdfinal

USE BDFINAL
DESCRIBE ACCESORIOS

CREATE TABLE ACCESROIOS
	Codigo 		DECIMAL(10,0) NOT NULL,
	Descripcion	VARCHAR(40),
	Marca		VARCHAR(40),
	Stock		INT(11),
	Pcompra		DOUBLE,
	Fcompra		INT
	PRIMARY KEY (Codigo));
)

INSERT INTO ACCESORIOS VALUES
('1','MousePad','Cybertel','5','80','2020-12-24')

SELECT * FROM ACCESORIOS

UPDATE ACCESORIOS SET Descripcion='Mouse',Marca='Asus',Stock='10',Pcompra='90',Fcompra='2020-12-30' WHERE Codigo='1';

DELETE FROM ACCESORIOS WHERE Codigo='2';

SELECT * FROM ACCESORIOS WHERE codigo='2';

